name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: publish
      run: dotnet publish -r win-x64 -c Release --self-contained
    - name: Upload artifact - Windows
      uses: actions/upload-artifact@v1.0.0
      with:
        name: WebScraper
        path: DevopsWebScraper/bin/Debug/netcoreapp3.1/
  
